spring:
  application:
    name: contract-app
  profiles:
    active: local
  xdisx:
    environment: LOCAL
    contract:
      openfeign:
        logLevel: BASIC
      customer:
        client-name: customer-app
      product:
        client-name: product-app
      document:
        client-name: document-app