name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Build and Push
      run: |
        echo ${{ secrets.GH_PAT }} | sudo docker login ghcr.io -u magraul --password-stdin
        gradle clean build -x test
        docker build . --file Dockerfile --tag ghcr.io/magraul/contract-app:latest
        docker push ghcr.io/magraul/contract-app:latest
