name: Pull Request Analysis

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Continous-PR-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew clean build

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io/'
        with:
          args: >
            -Dsonar.projectKey=xDisx_contract
            -Dsonar.organization=xdisx
            -Dsonar.sources=contract-app/src
            -Dsonar.java.binaries=contract-app/build/classes/java/main
            
